export enum CategoryType {
    BENTO_BOX_LUNCH = "BENTO_BOX_LUNCH",
    SUSHI_BAR_LUNCH = "SUSHI_BAR_LUNCH",
    RICE_AND_NOODLES_LUNCH = "RICE_AND_NOODLES_LUNCH",
    CHEFS_SPECIAL_ROLLS = "CHEFS_SPECIAL_ROLLS",
    SOUP = "SOUP",
    SALAD = "SALAD",
    HOT_APPETIZER = "HOT_APPETIZER",
    COLD_APPETIZER = "COLD_APPETIZER",
    KITCHEN_ENTREE = "KITCHEN_ENTREE",
    FRIED_RICE_AND_NOODLES = "FRIED_RICE_AND_NOODLES",
    SUSHI_BAR_ENTREE = "SUSHI_BAR_ENTREE",
    ILLUZION_TODAYS_SPECIAL = "ILLUZION_TODAYS_SPECIAL",
    SUSHI_AND_SASHIMI_A_LA_CARTE = "SUSHI_AND_SASHIMI_A_LA_CARTE",
    ROLLS_AND_HAND_ROLLS = "ROLLS_AND_HAND_ROLLS",
    DESSERTS = "DESSERTS",
    BEVERAGES = "BEVERAGES"
}